const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const people=[['维拉','秘书','#c9d9a3'],['隆巴德','冒险家','#d6a77a'],['沃格雷夫','退休法官','#ad9cc9'],['阿姆斯特朗','医生','#7fb0b2'],['布洛尔','前警探','#91bda2'],['布伦特','女士','#d7a0a8'],['麦克阿瑟','将军','#b7b898'],['马斯顿','青年','#87a7cf'],['罗杰斯','管家','#c6b5a0'],['罗杰斯太太','女管家','#aaaece']];
const rooms=[{id:'living',name:'客厅',floor:0,x:100,y:100,w:230,h:175,desc:'访客相聚的公共空间。留声机与座椅作为场景识别物件。',icon:'♧'},{id:'dining',name:'餐厅',floor:0,x:340,y:100,w:220,h:175,desc:'晚餐与桌上的小雕像，是观察人物关系的起点。',icon:'♜'},{id:'kitchen',name:'厨房',floor:0,x:570,y:100,w:145,h:175,desc:'服务区域，连接餐厅与内侧走廊。连接方式为演示推定。',icon:'♨'},{id:'hall',name:'入口大厅',floor:0,x:100,y:285,w:230,h:120,desc:'别墅入口，用于推演人物进出。',icon:'◇'},{id:'corridor',name:'走廊',floor:0,x:340,y:285,w:220,h:120,desc:'连接公共区域和楼梯的中间空间。',icon:'↔'},{id:'stairs',name:'楼梯',floor:0,x:570,y:285,w:145,h:120,desc:'连接一层与二层。模型未使用可验证的原文尺寸。',icon:'▤'},{id:'terrace',name:'海侧露台',floor:0,x:100,y:415,w:615,h:75,desc:'面向大海的户外观察点，边界与面积为展示补全。',icon:'≈'},...['维拉的房间','隆巴德的房间','法官的房间','医生的房间','其他客房','二层走廊'].map((name,i)=>({id:'upper'+i,name,floor:1,x:100+(i%3)*210,y:100+Math.floor(i/3)*165,w:200,h:155,desc:'客房相对位置为交互原型推定，不作为原作行动依据。',icon:'▣'})),{id:'shore',name:'登陆码头',floor:2,x:150,y:360,w:140,h:100,desc:'访客抵达孤岛的入口。地图轮廓为概念示意。',icon:'⚓'},{id:'villa',name:'海岛别墅',floor:2,x:350,y:170,w:240,h:180,desc:'十位访客所在的别墅。点击一层或二层浏览内部。',icon:'⌂'},{id:'cliff',name:'海岸岩壁',floor:2,x:600,y:340,w:120,h:115,desc:'海岛外缘。位置与距离为展示补全。',icon:'△'}];
const initialPositions=Object.fromEntries(people.map((_,i)=>[i,{room:i<6?'living':'dining',u:.22+(i%3)*.27,v:.3+Math.floor((i%6)/3)*.4,angle:0,note:''}]));
const blankPlan=(name='假说 A · 晚餐之后')=>({id:crypto.randomUUID(),name,note:'',nodes:[{t:0,label:'晚餐之后',positions:structuredClone(initialPositions)},{t:30,label:'自由调查',positions:structuredClone(initialPositions)},{t:60,label:'集合讨论',positions:structuredClone(initialPositions)}],routes:{}});
let data={plans:[blankPlan()],active:0,progress:2};try{let saved=JSON.parse(localStorage.getItem('mijing-v1'));if(saved?.plans?.length&&saved.plans.every(p=>p.nodes?.length))data=saved;}catch{}
let floor=0,view='3d',zoom=1,rotation=0,time=0,selectedRoom='living',selectedPerson=null,tab='object',showTrails=false,playing=null,history=[],drag=null;
const plan=()=>data.plans[data.active];const node=()=>[...plan().nodes].sort((a,b)=>a.t-b.t).filter(n=>n.t<=time).at(-1)||plan().nodes[0];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clock=t=>`${20+Math.floor(t/60)}:${String(t%60).padStart(2,'0')}`;
let backendReady=false,syncTimer;
function persist(){try{localStorage.setItem('mijing-v1',JSON.stringify(data));}catch{toast('浏览器存储不可用，请导出假说备份');}
if(backendReady){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncBackend(),650);}}
async function syncBackend(){try{const res=await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!res.ok)throw Error();$('.left-bottom').innerHTML='<span class="dot"></span> Java 后端 · 已同步';return true;}catch{$('.left-bottom').textContent='后端不可用 · 已保存在浏览器';return false;}}
async function loadBackend(){try{const res=await fetch('/api/state');if(!res.ok)throw Error();const saved=await res.json();if(saved!==null){if(!saved?.plans?.length||!saved.plans.every(p=>p.nodes?.length)||!saved.plans[saved.active])throw Error();data=saved;$('#progress').value=data.progress;}backendReady=true;render();$('.left-bottom').innerHTML='<span class="dot"></span> Java 后端 · 已连接';}catch{$('.left-bottom').textContent='后端未连接 · 本地模式';}}
function checkpoint(){history.push(JSON.stringify(data));if(history.length>40)history.shift();}
function toast(s){$('#toast').textContent=s;$('#toast').style.opacity=1;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.opacity=0,2600);}
function render(){renderLeft();renderMap();renderInspector();renderTimeline();persist();}
function renderLeft(){$('#rooms').innerHTML=rooms.filter(r=>r.floor===floor).map((r,i)=>`<button data-room="${r.id}" class="${r.id===selectedRoom?'selected':''}">${r.name}<span>0${i+1} ↗</span></button>`).join('');$('#characters').innerHTML=people.map((p,i)=>`<button class="character ${selectedPerson===i?'selected':''}" data-person="${i}" style="--c:${p[2]}"><span class="chip">${p[0][0]}</span>${p[0]}<small>${p[1]}</small></button>`).join('');$('#placed-count').textContent=Object.keys(node().positions).length;$$('[data-room]').forEach(b=>b.onclick=()=>{selectedRoom=b.dataset.room;selectedPerson=null;render();});$$('[data-person]').forEach(b=>b.onclick=()=>{selectedPerson=Number(b.dataset.person);tab='object';syncTabs();render();toast(`已选中${people[selectedPerson][0]}，点击房间放置`);});}
function matrix(){let a=rotation*Math.PI/180,c=Math.cos(a),s=Math.sin(a);let sx=view==='3d'?.86:1,sy=view==='3d'?.68:1,skew=view==='3d'?-.43:0;return {a:sx*c*zoom,b:sy*s*zoom,c:(-sx*s+skew)*zoom,d:sy*c*zoom};}
function renderMap(){let m=matrix(),cx=407,cy=300,tx=450-m.a*cx-m.c*cy,ty=310-m.b*cx-m.d*cy;let svg=`<defs><pattern id="grid" width="35" height="35" patternUnits="userSpaceOnUse"><path d="M 35 0 L 0 0 0 35" fill="none" stroke="#4d6753" stroke-width=".6" opacity=".17"/></pattern><filter id="shadow"><feDropShadow dx="4" dy="20" stdDeviation="12" flood-opacity=".4"/></filter></defs><rect width="900" height="620" fill="url(#grid)"/><g id="world" transform="matrix(${m.a} ${m.b} ${m.c} ${m.d} ${tx} ${ty})">`;
if(floor===2)svg+='<path d="M80 370 Q60 200 260 110 Q420 20 620 160 L780 310 Q800 450 600 510 L240 530Z" fill="#344a37" stroke="#61755a" stroke-width="5" filter="url(#shadow)"/><path d="M65 540 Q300 565 730 515 M60 570 Q300 595 760 550" fill="none" stroke="#567769" opacity=".3"/>';
else svg+='<path d="M75 80 H745 V510 H75Z" fill="#2c3c2e" stroke="#42533d" stroke-width="8" filter="url(#shadow)"/>';
rooms.filter(r=>r.floor===floor).forEach(r=>{let sel=selectedRoom===r.id;svg+=`<g class="room" data-maproom="${r.id}"><rect x="${r.x}" y="${r.y}" width="${r.w}" height="${r.h}" rx="2" fill="${sel?'#637351':r.id==='terrace'?'#344838':'#43513c'}" stroke="${sel?'#c3d29d':'#829071'}" stroke-width="${sel?3:2}"/>`;
if(view==='3d')svg+=`<path d="M${r.x} ${r.y+30}V${r.y}H${r.x+r.w}V${r.y+30}" fill="none" stroke="#849473" stroke-width="7" opacity=".9"/>`;
svg+=`<text x="${r.x+12}" y="${r.y+24}" fill="#d0d8bb" font-size="12" letter-spacing="2">${r.name}</text>`;
if(r.id==='living')svg+=`<rect x="140" y="153" width="92" height="35" rx="7" fill="#91a081"/><rect x="260" y="180" width="36" height="60" rx="4" fill="#788c6d"/><rect x="177" y="217" width="64" height="27" rx="4" fill="#283b2e" stroke="#9ba789"/>`;
if(r.id==='dining')svg+=`<rect x="393" y="160" width="112" height="62" rx="23" fill="#918568" stroke="#baab82"/>${Array.from({length:10},(_,i)=>`<circle cx="${407+i*9}" cy="188" r="2.5" fill="#d4c796"/>`).join('')}`;
if(r.id==='kitchen')svg+=`<path d="M585 140H695V250" fill="none" stroke="#92977b" stroke-width="22"/><circle cx="669" cy="150" r="9" fill="#3e5140"/>`;
if(r.id==='stairs'||r.id==='upper5')svg+=Array.from({length:7},(_,i)=>`<rect x="${r.x+35}" y="${r.y+38+i*9}" width="60" height="7" fill="#8d9a7f"/>`).join('');
if(r.id.startsWith('upper')&&r.id!=='upper5')svg+=`<rect x="${r.x+100}" y="${r.y+62}" width="65" height="75" rx="3" fill="#718566"/><rect x="${r.x+106}" y="${r.y+66}" width="53" height="20" rx="4" fill="#b8c0a4"/>`;
if(r.id==='terrace')svg+=Array.from({length:12},(_,i)=>`<path d="M${r.x+i*50} ${r.y}v75" stroke="#6d7a5b" opacity=".5"/>`).join('');svg+='</g>';});
if(showTrails){people.forEach((p,i)=>{let pts=plan().nodes.map(n=>n.positions[i]).filter(Boolean).filter(pos=>rooms.find(r=>r.id===pos.room)?.floor===floor).map(pos=>{let r=rooms.find(r=>r.id===pos.room);return `${r.x+r.w*pos.u},${r.y+r.h*pos.v}`;});if(pts.length>1)svg+=`<polyline points="${pts.join(' ')}" fill="none" stroke="${p[2]}" stroke-width="2" stroke-dasharray="5 5" opacity=".8"/>`;});}
Object.entries(node().positions).forEach(([i,pos])=>{let r=rooms.find(r=>r.id===pos.room);if(!r||r.floor!==floor)return;let p=people[i],x=r.x+r.w*pos.u,y=r.y+r.h*pos.v;svg+=`<g class="pawn" data-pawn="${i}" transform="translate(${x} ${y})"><ellipse cy="8" rx="13" ry="8" fill="#0006"/><path d="M-11 5L-7-10H7L11 5Z" fill="${p[2]}" stroke="#1a2920" stroke-width="2"/><circle cy="-17" r="8" fill="${p[2]}" stroke="${Number(i)===selectedPerson?'#fff':'#283b2b'}" stroke-width="${Number(i)===selectedPerson?3:1}"/><path d="M0 -31L4 -25H-4Z" fill="${p[2]}" transform="rotate(${pos.angle||0})"/><rect x="-27" y="15" width="54" height="17" rx="3" fill="#14221ee6"/><text y="27" text-anchor="middle" fill="${p[2]}" font-size="9">${p[0]}</text></g>`;});
svg+='</g>';$('#map').innerHTML=svg;$('#stage-label').textContent=['别墅一层','别墅二层','兵岛全景'][floor];$('#hint').textContent=selectedPerson===null?'点击房间查看 · 选择棋子后点击放置 · 拖动棋子移动':`正在放置 ${people[selectedPerson][0]} · 点击任意房间`;
}
function mapPoint(e){let pt=$('#map').createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;return pt.matrixTransform($('#world').getScreenCTM().inverse());}
function putPerson(i,e){let pt=mapPoint(e),r=rooms.find(r=>r.floor===floor&&pt.x>=r.x&&pt.x<=r.x+r.w&&pt.y>=r.y&&pt.y<=r.y+r.h);if(!r)return false;checkpoint();node().positions[i]={...node().positions[i],room:r.id,u:Math.max(.08,Math.min(.92,(pt.x-r.x)/r.w)),v:Math.max(.22,Math.min(.85,(pt.y-r.y)/r.h))};selectedRoom=r.id;render();return true;}
$('#map').addEventListener('pointerdown',e=>{let pawn=e.target.closest('[data-pawn]');if(pawn){selectedPerson=Number(pawn.dataset.pawn);drag={i:selectedPerson,x:e.clientX,y:e.clientY};$('#map').setPointerCapture(e.pointerId);render();}});
$('#map').addEventListener('pointerup',e=>{if(drag){let moved=Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>5;if(moved&&!putPerson(drag.i,e))toast('请将棋子放在房间内');drag=null;return;}let room=e.target.closest('[data-maproom]');if(!room)return;if(selectedPerson!==null){putPerson(selectedPerson,e);toast('位置已记录在 '+clock(node().t)+' 节点');}else{selectedRoom=room.dataset.maproom;render();}});
function syncTabs(){$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));}
function renderInspector(){if(tab==='clues'){$('#inspector').innerHTML=`<div class="eyebrow">CASE NOTES / 0${data.progress===1?1:3}</div><h2>已知线索</h2><div class="clue"><small>原作背景 · 抵达兵岛</small><p><strong>十位访客来到孤岛</strong></p><p>基本前提来自作者官网作品简介，不包含结局。</p></div>${data.progress>=2?'<div class="clue"><small>原作场景 · 晚餐之后</small><p><strong>餐桌上的十个小雕像</strong></p><p>仅展示物件概念，不提供后续变化。</p></div><div class="clue"><small>原作场景 · 晚餐之后</small><p><strong>客厅中的留声机</strong></p><p>仅作为空间识别物件；演示不复述录音。</p></div>':''}<label class="field">我的推理笔记<textarea id="plan-note" placeholder="记录你的疑问、证词与假设…">${escape(plan().note||'')}</textarea></label>`;$('#plan-note').onchange=e=>{checkpoint();plan().note=e.target.value;persist();};return;}
if(selectedPerson!==null){let p=people[selectedPerson],pos=node().positions[selectedPerson];$('#inspector').innerHTML=`<div class="object-icon" style="color:${p[2]}">♟</div><h2>${p[0]}</h2><span class="tag" style="margin:0">用户假设 · ${clock(node().t)}</span><div class="meta-row"><span>身份</span><b>${p[1]}</b></div><label class="field">所在空间<select id="person-room">${rooms.map(r=>`<option value="${r.id}" ${pos?.room===r.id?'selected':''}>${['一层','二层','岛屿'][r.floor]} / ${r.name}</option>`).join('')}</select></label><label class="field">朝向<select id="angle">${[0,90,180,270].map(a=>`<option value="${a}" ${pos?.angle===a?'selected':''}>${a}°</option>`).join('')}</select></label><label class="field">人物备注<textarea id="person-note" placeholder="这是我的假设…">${escape(pos?.note||'')}</textarea></label><button class="wide" id="remove-person">从当前节点移除棋子</button><p>移动只改变当前时间节点。其他节点保留各自的位置。</p>`;$('#person-room').onchange=e=>{checkpoint();let r=rooms.find(r=>r.id===e.target.value);node().positions[selectedPerson]={...pos,room:r.id,u:.5,v:.5};floor=r.floor;selectedRoom=r.id;syncFloors();render();};$('#angle').onchange=e=>{if(!pos)return;checkpoint();pos.angle=Number(e.target.value);render();};$('#person-note').onchange=e=>{if(!pos)return;checkpoint();pos.note=e.target.value;persist();};$('#remove-person').onclick=()=>{checkpoint();delete node().positions[selectedPerson];selectedPerson=null;render();};return;}
let r=rooms.find(r=>r.id===selectedRoom)||rooms.find(r=>r.floor===floor);$('#inspector').innerHTML=`<div class="eyebrow">SPACE / ${r.id.toUpperCase()}</div><div class="object-icon" style="margin-top:14px">${r.icon}</div><h2>${r.name}</h2><span class="tag" style="margin:0">编辑推定</span><p>${r.desc}</p><div class="meta-row"><span>所在楼层</span><b>${['一层 · 公共区域','二层 · 客房区域','岛屿 · 外部空间'][r.floor]}</b></div><div class="meta-row"><span>当前位置人数</span><b>${Object.values(node().positions).filter(p=>p.room===r.id).length} 人</b></div><div class="meta-row"><span>尺寸依据</span><b>未核实 / 示意比例</b></div><p>房间关系为原型补全。不能用模型比例推断精确距离或行动耗时。</p><button id="focus-room" class="wide">⌖ 聚焦此空间</button>`;$('#focus-room').onclick=()=>{zoom=1.3;renderMap();};}
function renderTimeline(){$('#time-now').textContent=clock(time);$('#scrubber').value=time;$('#plan-select').innerHTML=data.plans.map((p,i)=>`<option value="${i}" ${i===data.active?'selected':''}>${escape(p.name)}</option>`).join('');$('#nodes').innerHTML=[...plan().nodes].sort((a,b)=>a.t-b.t).map(n=>`<button data-time="${n.t}" class="node ${node()===n?'active':''}">${clock(n.t)}<span>${escape(n.label)}</span></button>`).join('');$$('[data-time]').forEach(b=>b.onclick=()=>{time=Number(b.dataset.time);render();});}
function syncFloors(){$$('[data-floor]').forEach(b=>b.classList.toggle('active',Number(b.dataset.floor)===floor));}
$$('[data-floor]').forEach(b=>b.onclick=()=>{floor=Number(b.dataset.floor);selectedRoom=rooms.find(r=>r.floor===floor).id;syncFloors();render();});
$$('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;syncTabs();renderInspector();});
$('#view3d').onclick=()=>setView('3d');$('#view2d').onclick=()=>setView('2d');function setView(v){view=v;$('#view3d').classList.toggle('active',v==='3d');$('#view2d').classList.toggle('active',v==='2d');renderMap();}
$('#zoomin').onclick=()=>{zoom=Math.min(1.8,zoom+.15);renderMap();};$('#zoomout').onclick=()=>{zoom=Math.max(.5,zoom-.15);renderMap();};$('#resetview').onclick=()=>{zoom=1;rotation=0;renderMap();};$('#rotate').onclick=()=>{rotation=(rotation+15)%360;renderMap();};$('#trails').onclick=()=>{showTrails=!showTrails;$('#trails').classList.toggle('active',showTrails);renderMap();};$('#undo').onclick=()=>{if(!history.length)return toast('暂无可撤销的操作');data=JSON.parse(history.pop());render();toast('已撤销');};
$('#progress').value=data.progress;$('#progress').onchange=e=>{data.progress=Number(e.target.value);render();toast('阅读进度已更新，线索按进度显示');};
$('#scrubber').oninput=e=>{time=Number(e.target.value);renderMap();renderTimeline();renderInspector();};
function stop(){clearInterval(playing);playing=null;$('#play').textContent='▶';}
$('#play').onclick=()=>{if(playing){stop();return;}if(time>=120)time=0;$('#play').textContent='Ⅱ';playing=setInterval(()=>{time=Math.min(120,time+Number($('#speed').value));renderMap();renderTimeline();renderInspector();if(time>=120)stop();},500);};
$('#plan-select').onchange=e=>{stop();data.active=Number(e.target.value);time=0;render();};
function modal(html){$('#modal-content').innerHTML=html;$('#modal').showModal();}
$('#addnode').onclick=()=>{stop();modal(`<div class="eyebrow">TIMELINE EDITOR</div><h2>记录一个新的时刻</h2><p>新节点复制当前人物位置。时间为演示设定，范围 20:00—22:00。</p><label class="field">时刻<input id="node-time" type="time" value="${clock(time)}" min="20:00" max="22:00"></label><label class="field">事件名称<input id="node-label" maxlength="40" value="新的行动"></label><button id="confirm-node" class="primary wide">创建时间节点</button>`);$('#confirm-node').onclick=()=>{let [h,m]=$('#node-time').value.split(':').map(Number),t=(h-20)*60+m;if(!Number.isFinite(t)||t<0||t>120)return toast('请选择 20:00—22:00 内的时刻');if(plan().nodes.some(n=>n.t===t))return toast('此时刻已有节点，请选择其他时间');checkpoint();plan().nodes.push({t,label:$('#node-label').value.trim()||'新的行动',positions:structuredClone(node().positions)});time=t;$('#modal').close();render();toast('时间节点已创建');};};
$('#newplan').onclick=()=>{modal(`<div class="eyebrow">HYPOTHESIS</div><h2>建立另一种可能</h2><input id="plan-name" maxlength="50" placeholder="例如：假说 B · 经过露台"><button id="create-plan" class="primary wide">复制当前假说并创建</button>`);$('#create-plan').onclick=()=>{checkpoint();let p=structuredClone(plan());p.id=crypto.randomUUID();p.name=$('#plan-name').value.trim()||`假说 ${data.plans.length+1}`;data.plans.push(p);data.active=data.plans.length-1;$('#modal').close();render();toast('新假说已创建');};};
$('#save').onclick=async()=>{persist();if(backendReady){clearTimeout(syncTimer);toast(await syncBackend()?'假说已保存到 Java 后端':'后端保存失败，已保留浏览器副本');}else toast('假说已保存至此浏览器');};$('#mode').onclick=()=>{modal('<div class="eyebrow">EXPLORATION MODE</div><h2>自由推演</h2><p>1. 选择左侧人物，点击房间或拖动棋子。<br>2. 新建时间节点，记录下一时刻的位置。<br>3. 播放时间线，查看每个节点的状态。<br>4. 建立多个假说，记录笔记并保存。</p><p>当前 Demo 提供节点状态回放；连线仅表示位置变化，不代表原作路线。真相复盘尚未开放。</p>');};
$('#check').onclick=()=>{let ordered=[...plan().nodes].sort((a,b)=>a.t-b.t),warnings=[];for(let n=1;n<ordered.length;n++){for(let i=0;i<people.length;i++){let a=ordered[n-1].positions[i],b=ordered[n].positions[i];if(a&&b&&a.room!==b.room&&rooms.find(r=>r.id===a.room).floor!==rooms.find(r=>r.id===b.room).floor)warnings.push(`${people[i][0]}在 ${clock(ordered[n-1].t)}—${clock(ordered[n].t)} 跨楼层移动，尚未记录楼梯或外部路线。`);}}$('#check-result').textContent=warnings.length?warnings.join(' '):'未发现跨楼层移动。距离与实际耗时缺少依据，无法判断；本检查不能证明假说成立。';};
function openPage(page){$$('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#desk').hidden=page!=='desk';$('#other-page').hidden=page==='desk';if(page==='library'){$('#other-page').innerHTML=`<div class="eyebrow">THE CASE LIBRARY</div><h2>每一本书，都是一个待解的世界。</h2><p class="muted">作品档案 / 首个原型案例</p><article class="book-card"><div class="book-cover"><span>无人生还</span><small style="font-size:9px;margin-top:30px">AND THEN THERE WERE NONE</small></div><div class="eyebrow">AGATHA CHRISTIE</div><h2 style="font-size:25px">无人生还</h2><p>十位陌生人受邀来到孤立的兵岛。走进别墅，整理空间，摆出你自己的推理。</p><p>已支持：两层别墅与岛屿示意 · 十枚人物棋子 · 时间节点 · 多假说<br>模型属于编辑推定；中文译本章节未绑定，阅读进度采用场景节点。</p><button class="primary" id="enter">进入场景工作台 ↗</button></article><p class="small muted">背景来源：<a style="color:var(--mint)" href="https://www.agathachristie.com/en/stories/and-then-there-were-none" target="_blank" rel="noreferrer">Agatha Christie 官方作品介绍</a> · 未使用书籍封面或原文长段落。</p>`;$('#enter').onclick=()=>openPage('desk');}if(page==='plans'){renderPlans();}}
function renderPlans(){$('#other-page').innerHTML=`<div class="eyebrow">YOUR DEDUCTION NOTEBOOK</div><h2>保存每一种可能。</h2><p class="muted">所有方案保存在当前浏览器，可导出备份。</p>${data.plans.map((p,i)=>`<article class="plan-card"><div class="eyebrow">无人生还 / ${p.nodes.length} 个时间节点</div><h3>${escape(p.name)}</h3><p class="muted small">${escape(p.note||'还没有推理笔记')}</p><button data-openplan="${i}" class="primary">继续推演 ↗</button> <button data-rename="${i}">重命名</button> <button data-export="${i}">导出 JSON</button> <button data-delete="${i}" ${data.plans.length===1?'disabled':''}>删除</button></article>`).join('')}`;$$('[data-openplan]').forEach(b=>b.onclick=()=>{data.active=Number(b.dataset.openplan);time=0;render();openPage('desk');});$$('[data-rename]').forEach(b=>b.onclick=()=>{let i=Number(b.dataset.rename);modal(`<h2>重命名假说</h2><input id="rename-input" value="${escape(data.plans[i].name)}" maxlength="50"><button id="rename-confirm" class="primary wide">保存名称</button>`);$('#rename-confirm').onclick=()=>{let name=$('#rename-input').value.trim();if(!name)return;checkpoint();data.plans[i].name=name;persist();$('#modal').close();renderPlans();renderTimeline();};});$$('[data-delete]').forEach(b=>b.onclick=()=>{let i=Number(b.dataset.delete);modal(`<h2>删除这条假说？</h2><p>${escape(data.plans[i].name)} · 删除后可以使用工作台撤销恢复。</p><button id="delete-confirm" class="wide">确认删除</button>`);$('#delete-confirm').onclick=()=>{checkpoint();data.plans.splice(i,1);data.active=Math.min(data.active,data.plans.length-1);persist();$('#modal').close();renderPlans();render();};});$$('[data-export]').forEach(b=>b.onclick=()=>{let p=data.plans[Number(b.dataset.export)],url=URL.createObjectURL(new Blob([JSON.stringify({scene:'soldier-island-prototype-v1',hypothesis:p},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='mijing-hypothesis.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('假说已导出');});}
$$('[data-page]').forEach(b=>b.onclick=()=>{stop();openPage(b.dataset.page);});render();loadBackend();
